
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 12 2024 10:13:00

// Verification Directory fv/synth_wrapper 

module alu(clk_i, rst_ni, op_i, a_i, b_i, result_o, carry_o);
  input clk_i, rst_ni;
  input [2:0] op_i;
  input [3:0] a_i, b_i;
  output [3:0] result_o;
  output carry_o;
  wire clk_i, rst_ni;
  wire [2:0] op_i;
  wire [3:0] a_i, b_i;
  wire [3:0] result_o;
  wire carry_o;
  wire n_0, n_2, n_3, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_35, n_36, n_37;
  wire n_38, n_40, n_42, n_43, n_44, n_45, n_46, n_48;
  wire n_49, n_50, n_51, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_60, n_61, n_62, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_72, n_73, n_74, n_75, n_78;
  wire n_80, n_81, n_82, n_83, n_84, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_96, n_97, n_98;
  wire n_101, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_113, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_127, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_137, n_138, n_140, n_143;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_153;
  wire n_154, n_156, n_157, n_158, n_159, n_160, n_162, n_163;
  wire n_165, n_166, n_168, n_170, n_172, n_175, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_258, n_259;
  wire n_260, n_261, n_262, n_263, n_266, n_267, n_268, n_269;
  wire n_270, n_271, n_272, n_273, n_277, n_278, n_279, n_280;
  wire n_281, n_282, n_306, n_307, n_308, n_309, n_310, n_311;
  wire n_356, n_367, n_373, n_404, n_461;
  sky130_fd_sc_hd__dfrtp_1 \result_o_reg[3] (.RESET_B (rst_ni), .CLK
       (clk_i), .D (n_175), .Q (result_o[3]));
  sky130_fd_sc_hd__dfrtp_1 carry_o_reg(.RESET_B (rst_ni), .CLK (clk_i),
       .D (n_267), .Q (carry_o));
  sky130_fd_sc_hd__dfrtp_1 \result_o_reg[2] (.RESET_B (rst_ni), .CLK
       (clk_i), .D (n_172), .Q (result_o[2]));
  sky130_fd_sc_hd__nand3_1 g6853(.A (n_282), .B (n_157), .C (n_163), .Y
       (n_175));
  sky130_fd_sc_hd__dfrtp_1 \result_o_reg[1] (.RESET_B (rst_ni), .CLK
       (clk_i), .D (n_170), .Q (result_o[1]));
  sky130_fd_sc_hd__nand4_1 g6857(.A (n_160), .B (n_168), .C (n_154), .D
       (n_166), .Y (n_172));
  sky130_fd_sc_hd__dfrtp_1 \result_o_reg[0] (.RESET_B (rst_ni), .CLK
       (clk_i), .D (n_273), .Q (result_o[0]));
  sky130_fd_sc_hd__nand4_1 g6860(.A (n_147), .B (n_165), .C (n_151), .D
       (n_130), .Y (n_170));
  sky130_fd_sc_hd__nand2_1 g6862(.A (n_203), .B (n_72), .Y (n_168));
  sky130_fd_sc_hd__nand2b_1 g6864(.A_N (n_72), .B (n_158), .Y (n_166));
  sky130_fd_sc_hd__nand2_1 g6865(.A (n_260), .B (n_149), .Y (n_165));
  sky130_fd_sc_hd__clkinv_1 g6867(.A (n_159), .Y (n_163));
  sky130_fd_sc_hd__o21a_1 g6869(.A1 (n_110), .A2 (n_461), .B1 (n_143),
       .X (n_160));
  sky130_fd_sc_hd__nand2_1 g6870(.A (n_145), .B (n_129), .Y (n_159));
  sky130_fd_sc_hd__nand2_2 g6871(.A (n_153), .B (n_51), .Y (n_162));
  sky130_fd_sc_hd__o21ai_1 g6872(.A1 (n_262), .A2 (n_135), .B1 (n_204),
       .Y (n_158));
  sky130_fd_sc_hd__nor2_2 g6873(.A (n_146), .B (n_150), .Y (n_157));
  sky130_fd_sc_hd__nand2_1 g6874(.A (n_277), .B (n_57), .Y (n_156));
  sky130_fd_sc_hd__o21a_1 g6876(.A1 (n_0), .A2 (n_120), .B1 (n_97), .X
       (n_154));
  sky130_fd_sc_hd__nand2_2 g6877(.A (n_134), .B (n_49), .Y (n_153));
  sky130_fd_sc_hd__nand2_1 g6879(.A (n_132), .B (n_281), .Y (n_151));
  sky130_fd_sc_hd__nand3_2 g6880(.A (n_131), .B (n_119), .C (n_90), .Y
       (n_150));
  sky130_fd_sc_hd__o21ai_1 g6881(.A1 (n_6), .A2 (n_121), .B1 (n_81), .Y
       (n_149));
  sky130_fd_sc_hd__nand2_1 g6882(.A (n_135), .B (n_281), .Y (n_148));
  sky130_fd_sc_hd__nor2_2 g6883(.A (n_124), .B (n_140), .Y (n_147));
  sky130_fd_sc_hd__a21oi_1 g6884(.A1 (n_205), .A2 (n_56), .B1 (n_93),
       .Y (n_146));
  sky130_fd_sc_hd__nand3_2 g6885(.A (n_308), .B (n_138), .C (n_113), .Y
       (n_145));
  sky130_fd_sc_hd__nand4b_1 g6887(.A_N (n_259), .B (n_122), .C (n_101),
       .D (n_111), .Y (n_143));
  sky130_fd_sc_hd__a21oi_2 g6890(.A1 (n_108), .A2 (n_306), .B1 (n_75),
       .Y (n_140));
  sky130_fd_sc_hd__nand2_2 g6892(.A (n_121), .B (n_8), .Y (n_138));
  sky130_fd_sc_hd__o21ai_1 g6893(.A1 (n_404), .A2 (n_70), .B1 (n_89),
       .Y (n_137));
  sky130_fd_sc_hd__inv_1 g6895(.A (n_134), .Y (n_135));
  sky130_fd_sc_hd__nand3_1 g6896(.A (n_123), .B (n_101), .C (n_96), .Y
       (n_133));
  sky130_fd_sc_hd__xnor2_2 g6897(.A (n_80), .B (n_20), .Y (n_132));
  sky130_fd_sc_hd__nand2_2 g6898(.A (n_118), .B (n_205), .Y (n_131));
  sky130_fd_sc_hd__o21ai_1 g6899(.A1 (n_9), .A2 (n_84), .B1 (n_117), .Y
       (n_130));
  sky130_fd_sc_hd__nand3b_1 g6900(.A_N (n_404), .B (n_103), .C (n_109),
       .Y (n_129));
  sky130_fd_sc_hd__nand2_2 g6901(.A (n_125), .B (n_48), .Y (n_134));
  sky130_fd_sc_hd__nand2_1 g6902(.A (n_311), .B (n_6), .Y (n_127));
  sky130_fd_sc_hd__nand2_2 g6904(.A (n_45), .B (n_42), .Y (n_125));
  sky130_fd_sc_hd__and2b_1 g6905(.A_N (n_40), .B (n_91), .X (n_124));
  sky130_fd_sc_hd__o21ai_1 g6906(.A1 (n_54), .A2 (n_259), .B1 (n_81),
       .Y (n_123));
  sky130_fd_sc_hd__o21ai_1 g6907(.A1 (n_16), .A2 (n_68), .B1 (n_8), .Y
       (n_122));
  sky130_fd_sc_hd__nand3b_1 g6910(.A_N (n_81), .B (n_67), .C (n_55), .Y
       (n_119));
  sky130_fd_sc_hd__nor2_2 g6911(.A (n_75), .B (n_107), .Y (n_118));
  sky130_fd_sc_hd__o21ai_1 g6912(.A1 (n_404), .A2 (n_80), .B1 (n_89),
       .Y (n_117));
  sky130_fd_sc_hd__nand2_2 g6915(.A (n_105), .B (n_106), .Y (n_121));
  sky130_fd_sc_hd__nand2_1 g6916(.A (n_104), .B (n_98), .Y (n_120));
  sky130_fd_sc_hd__nand2_1 g6920(.A (n_55), .B (n_87), .Y (n_111));
  sky130_fd_sc_hd__nor2_1 g6921(.A (n_32), .B (n_84), .Y (n_110));
  sky130_fd_sc_hd__nand2_1 g6922(.A (n_83), .B (n_17), .Y (n_109));
  sky130_fd_sc_hd__nand2_1 g6923(.A (n_80), .B (n_18), .Y (n_108));
  sky130_fd_sc_hd__nand2_1 g6924(.A (n_64), .B (n_56), .Y (n_107));
  sky130_fd_sc_hd__nand2_2 g6925(.A (n_69), .B (n_15), .Y (n_106));
  sky130_fd_sc_hd__nand2_2 g6926(.A (n_68), .B (n_309), .Y (n_105));
  sky130_fd_sc_hd__nand2_1 g6927(.A (n_87), .B (n_310), .Y (n_104));
  sky130_fd_sc_hd__nand2_1 g6928(.A (n_89), .B (n_65), .Y (n_103));
  sky130_fd_sc_hd__nand2_1 g6931(.A (n_87), .B (n_44), .Y (n_113));
  sky130_fd_sc_hd__nand2_1 g6933(.A (n_66), .B (n_309), .Y (n_98));
  sky130_fd_sc_hd__nand3b_1 g6935(.A_N (n_40), .B (n_73), .C (n_60), .Y
       (n_97));
  sky130_fd_sc_hd__nand2_1 g6936(.A (n_55), .B (n_68), .Y (n_96));
  sky130_fd_sc_hd__nand2_1 g6938(.A (n_55), .B (n_69), .Y (n_94));
  sky130_fd_sc_hd__nand2_1 g6939(.A (n_74), .B (n_65), .Y (n_93));
  sky130_fd_sc_hd__o21ai_1 g6940(.A1 (op_i[0]), .A2 (n_18), .B1 (n_61),
       .Y (n_92));
  sky130_fd_sc_hd__o21ai_1 g6941(.A1 (n_9), .A2 (n_21), .B1 (n_62), .Y
       (n_91));
  sky130_fd_sc_hd__a211o_1 g6942(.A1 (n_57), .A2 (n_21), .B1 (n_40),
       .C1 (n_58), .X (n_90));
  sky130_fd_sc_hd__nand2_1 g6943(.A (n_44), .B (n_69), .Y (n_101));
  sky130_fd_sc_hd__inv_2 g6945(.A (n_88), .Y (n_89));
  sky130_fd_sc_hd__inv_2 g6947(.A (n_83), .Y (n_84));
  sky130_fd_sc_hd__clkinv_1 g6948(.A (n_81), .Y (n_82));
  sky130_fd_sc_hd__inv_2 g6951(.A (n_78), .Y (n_80));
  sky130_fd_sc_hd__inv_2 g6953(.A (n_75), .Y (n_74));
  sky130_fd_sc_hd__nand2_1 g6954(.A (n_56), .B (n_21), .Y (n_73));
  sky130_fd_sc_hd__nor2_2 g6955(.A (n_21), .B (n_53), .Y (n_88));
  sky130_fd_sc_hd__nand3_2 g6956(.A (a_i[2]), .B (n_26), .C (n_24), .Y
       (n_87));
  sky130_fd_sc_hd__nand3_2 g6959(.A (n_21), .B (op_i[2]), .C (n_33), .Y
       (n_81));
  sky130_fd_sc_hd__nand2_2 g6960(.A (n_48), .B (n_45), .Y (n_78));
  sky130_fd_sc_hd__nand3b_4 g6962(.A_N (op_i[0]), .B (n_31), .C (n_35),
       .Y (n_75));
  sky130_fd_sc_hd__inv_1 g6963(.A (n_3), .Y (n_72));
  sky130_fd_sc_hd__inv_1 g6964(.A (n_66), .Y (n_67));
  sky130_fd_sc_hd__inv_2 g6965(.A (n_64), .Y (n_65));
  sky130_fd_sc_hd__o21ai_1 g6967(.A1 (a_i[1]), .A2 (op_i[0]), .B1
       (n_6), .Y (n_62));
  sky130_fd_sc_hd__a21oi_1 g6968(.A1 (n_310), .A2 (n_29), .B1 (n_40),
       .Y (n_61));
  sky130_fd_sc_hd__o21a_1 g6970(.A1 (n_29), .A2 (n_16), .B1 (n_43), .X
       (n_70));
  sky130_fd_sc_hd__nand3_2 g6971(.A (n_26), .B (n_23), .C (a_i[1]), .Y
       (n_69));
  sky130_fd_sc_hd__nand3_2 g6972(.A (n_26), .B (n_22), .C (n_28), .Y
       (n_68));
  sky130_fd_sc_hd__nand3_2 g6973(.A (n_26), .B (n_22), .C (n_2), .Y
       (n_66));
  sky130_fd_sc_hd__nand2_1 g6974(.A (n_46), .B (n_19), .Y (n_64));
  sky130_fd_sc_hd__inv_2 g6976(.A (n_54), .Y (n_55));
  sky130_fd_sc_hd__nand2_1 g6979(.A (n_32), .B (n_367), .Y (n_51));
  sky130_fd_sc_hd__nor2_2 g6980(.A (op_i[2]), .B (n_33), .Y (n_50));
  sky130_fd_sc_hd__nand2_1 g6981(.A (n_26), .B (n_32), .Y (n_60));
  sky130_fd_sc_hd__nor2_2 g6982(.A (n_2), .B (n_25), .Y (n_58));
  sky130_fd_sc_hd__nand2_1 g6983(.A (n_2), .B (n_25), .Y (n_57));
  sky130_fd_sc_hd__nand2_2 g6984(.A (b_i[2]), .B (a_i[2]), .Y (n_56));
  sky130_fd_sc_hd__nand2_1 g6985(.A (n_26), .B (n_356), .Y (n_49));
  sky130_fd_sc_hd__nand2_2 g6986(.A (n_15), .B (n_7), .Y (n_54));
  sky130_fd_sc_hd__nand2_2 g6987(.A (n_35), .B (op_i[2]), .Y (n_53));
  sky130_fd_sc_hd__inv_2 g6990(.A (n_43), .Y (n_20));
  sky130_fd_sc_hd__inv_2 g6991(.A (n_42), .Y (n_43));
  sky130_fd_sc_hd__inv_2 g6992(.A (n_37), .Y (n_42));
  sky130_fd_sc_hd__inv_2 g6995(.A (n_36), .Y (n_18));
  sky130_fd_sc_hd__nand2_1 g6997(.A (n_10), .B (n_7), .Y (n_38));
  sky130_fd_sc_hd__nand2_2 g6998(.A (n_11), .B (n_6), .Y (n_48));
  sky130_fd_sc_hd__nand2_1 g6999(.A (n_30), .B (b_i[3]), .Y (n_46));
  sky130_fd_sc_hd__nand2_2 g7000(.A (n_7), .B (a_i[1]), .Y (n_45));
  sky130_fd_sc_hd__and2_1 g7001(.A (n_5), .B (b_i[0]), .X (n_44));
  sky130_fd_sc_hd__nand2_1 g7002(.A (n_23), .B (a_i[3]), .Y (n_19));
  sky130_fd_sc_hd__nand2_1 g7003(.A (b_i[0]), .B (n_27), .Y (n_37));
  sky130_fd_sc_hd__nand2_1 g7004(.A (a_i[0]), .B (b_i[0]), .Y (n_36));
  sky130_fd_sc_hd__nand2_2 g7005(.A (n_31), .B (n_33), .Y (n_40));
  sky130_fd_sc_hd__inv_4 g7006(.A (n_35), .Y (n_33));
  sky130_fd_sc_hd__inv_4 g7008(.A (op_i[1]), .Y (n_35));
  sky130_fd_sc_hd__clkinv_2 g7009(.A (a_i[2]), .Y (n_32));
  sky130_fd_sc_hd__clkinv_2 g7019(.A (op_i[2]), .Y (n_31));
  sky130_fd_sc_hd__inv_2 g7021(.A (n_30), .Y (n_17));
  sky130_fd_sc_hd__inv_2 g7022(.A (a_i[3]), .Y (n_30));
  sky130_fd_sc_hd__inv_2 g7023(.A (n_28), .Y (n_29));
  sky130_fd_sc_hd__buf_2 g7024(.A (a_i[0]), .X (n_28));
  sky130_fd_sc_hd__clkinv_1 g7025(.A (a_i[0]), .Y (n_27));
  sky130_fd_sc_hd__clkinv_4 g7026(.A (b_i[2]), .Y (n_26));
  sky130_fd_sc_hd__inv_2 g7027(.A (n_24), .Y (n_25));
  sky130_fd_sc_hd__inv_2 g7028(.A (b_i[3]), .Y (n_24));
  sky130_fd_sc_hd__inv_2 g7029(.A (b_i[3]), .Y (n_23));
  sky130_fd_sc_hd__inv_2 g7030(.A (b_i[3]), .Y (n_22));
  sky130_fd_sc_hd__inv_2 g7031(.A (op_i[0]), .Y (n_21));
  sky130_fd_sc_hd__inv_1 fopt7034(.A (n_15), .Y (n_16));
  sky130_fd_sc_hd__inv_2 fopt7035(.A (b_i[0]), .Y (n_15));
  sky130_fd_sc_hd__inv_1 fopt7040(.A (a_i[1]), .Y (n_11));
  sky130_fd_sc_hd__inv_2 fopt7041(.A (a_i[1]), .Y (n_10));
  sky130_fd_sc_hd__inv_1 fopt7042(.A (a_i[1]), .Y (n_9));
  sky130_fd_sc_hd__inv_1 fopt7044(.A (n_7), .Y (n_8));
  sky130_fd_sc_hd__inv_2 fopt7045(.A (b_i[1]), .Y (n_7));
  sky130_fd_sc_hd__inv_4 fopt7049(.A (n_5), .Y (n_6));
  sky130_fd_sc_hd__inv_2 fopt7050(.A (b_i[1]), .Y (n_5));
  sky130_fd_sc_hd__buf_1 drc_bufs7065(.A (n_198), .X (n_3));
  sky130_fd_sc_hd__buf_6 fopt7075(.A (a_i[3]), .X (n_2));
  sky130_fd_sc_hd__nand2b_1 g7079(.A_N (n_8), .B (n_82), .Y (n_0));
  sky130_fd_sc_hd__buf_1 g7080(.A (op_i[0]), .X (n_83));
  sky130_fd_sc_hd__xor2_1 g7082(.A (b_i[2]), .B (n_32), .X (n_198));
  sky130_fd_sc_hd__o21ai_1 g7083(.A1 (n_75), .A2 (n_202), .B1 (n_148),
       .Y (n_203));
  sky130_fd_sc_hd__buf_1 g1(.A (n_201), .X (n_202));
  sky130_fd_sc_hd__nand2_4 g7084(.A (n_199), .B (n_200), .Y (n_201));
  sky130_fd_sc_hd__nand2_2 g7085(.A (n_18), .B (n_38), .Y (n_199));
  sky130_fd_sc_hd__nand2_1 g7086(.A (n_6), .B (a_i[1]), .Y (n_200));
  sky130_fd_sc_hd__nand2_1 g7087(.A (n_74), .B (n_201), .Y (n_204));
  sky130_fd_sc_hd__nand2_4 g7088(.A (n_201), .B (n_60), .Y (n_205));
  sky130_fd_sc_hd__nand2_1 g58(.A (n_258), .B (n_259), .Y (n_260));
  sky130_fd_sc_hd__nand4_1 g60(.A (n_127), .B (n_82), .C (n_113), .D
       (n_94), .Y (n_258));
  sky130_fd_sc_hd__nand3_2 g59(.A (n_33), .B (op_i[0]), .C (op_i[2]),
       .Y (n_259));
  sky130_fd_sc_hd__nand2_1 g57(.A (n_261), .B (n_266), .Y (n_267));
  sky130_fd_sc_hd__nand2_1 g7129(.A (n_156), .B (n_74), .Y (n_261));
  sky130_fd_sc_hd__nand2b_1 g7130(.A_N (n_262), .B (n_307), .Y (n_266));
  sky130_fd_sc_hd__nand2_1 g62(.A (n_50), .B (op_i[0]), .Y (n_262));
  sky130_fd_sc_hd__nand2_1 g61(.A (n_19), .B (n_162), .Y (n_263));
  sky130_fd_sc_hd__nand4_1 g114(.A (n_268), .B (n_270), .C (n_272), .D
       (n_373), .Y (n_273));
  sky130_fd_sc_hd__o21ai_1 g115(.A1 (n_29), .A2 (n_84), .B1 (n_137), .Y
       (n_268));
  sky130_fd_sc_hd__nand2b_1 g116(.A_N (n_133), .B (n_269), .Y (n_270));
  sky130_fd_sc_hd__nand2_1 g118(.A (n_120), .B (n_6), .Y (n_269));
  sky130_fd_sc_hd__a21o_1 g117(.A1 (n_271), .A2 (n_75), .B1 (n_70), .X
       (n_272));
  sky130_fd_sc_hd__clkbuf_1 g7132(.A (n_262), .X (n_271));
  sky130_fd_sc_hd__a21o_1 g13(.A1 (n_205), .A2 (n_56), .B1 (n_58), .X
       (n_277));
  sky130_fd_sc_hd__nand3_1 g46(.A (n_279), .B (n_280), .C (n_281), .Y
       (n_282));
  sky130_fd_sc_hd__nand2_1 g48(.A (n_278), .B (n_65), .Y (n_279));
  sky130_fd_sc_hd__clkinv_1 g50(.A (n_162), .Y (n_278));
  sky130_fd_sc_hd__nand2b_1 g47(.A_N (n_65), .B (n_162), .Y (n_280));
  sky130_fd_sc_hd__inv_2 g49(.A (n_262), .Y (n_281));
  sky130_fd_sc_hd__nand2b_1 g7145(.A_N (n_18), .B (n_78), .Y (n_306));
  sky130_fd_sc_hd__nand2_1 g7146(.A (n_263), .B (n_46), .Y (n_307));
  sky130_fd_sc_hd__a21oi_2 g7147(.A1 (n_55), .A2 (n_66), .B1 (n_259),
       .Y (n_308));
  sky130_fd_sc_hd__nand4_1 g22(.A (n_17), .B (n_26), .C (n_310), .D
       (n_24), .Y (n_311));
  sky130_fd_sc_hd__inv_2 g23(.A (n_309), .Y (n_310));
  sky130_fd_sc_hd__clkbuf_2 g7148(.A (b_i[0]), .X (n_309));
  sky130_fd_sc_hd__buf_1 drc_bufs7186(.A (a_i[2]), .X (n_356));
  sky130_fd_sc_hd__buf_1 drc_bufs7196(.A (b_i[2]), .X (n_367));
  sky130_fd_sc_hd__buf_1 drc_bufs(.A (n_92), .X (n_373));
  sky130_fd_sc_hd__clkbuf_2 fopt(.A (n_53), .X (n_404));
  sky130_fd_sc_hd__a21o_1 g2(.A1 (n_89), .A2 (n_198), .B1 (n_404), .X
       (n_461));
endmodule

module synth_wrapper(clk, rst_n, op, a, b, result, carry);
  input clk, rst_n;
  input [2:0] op;
  input [3:0] a, b;
  output [3:0] result;
  output carry;
  wire clk, rst_n;
  wire [2:0] op;
  wire [3:0] a, b;
  wire [3:0] result;
  wire carry;
  wire [2:0] op_reg;
  wire [3:0] a_reg;
  wire [3:0] b_reg;
  wire carry_reg_48, n_0, n_1, n_3, n_4, n_5, n_7, n_8;
  wire \result_reg[0]_36 , \result_reg[1]_37 , \result_reg[2]_38 ,
       \result_reg[3]_39 ;
  alu ALU0(clk, rst_n, {n_4, op_reg[1], n_5}, a_reg, {b_reg[3], n_3,
       b_reg[1:0]}, {\result_reg[3]_39 , \result_reg[2]_38 ,
       \result_reg[1]_37 , \result_reg[0]_36 }, carry_reg_48);
  sky130_fd_sc_hd__dfrtp_1 \result_reg[3] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[3]_39 ), .Q (result[3]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[2]_38 ), .Q (result[2]));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[0]_36 ), .Q (result[0]));
  sky130_fd_sc_hd__dfrtp_1 carry_reg(.RESET_B (rst_n), .CLK (clk), .D
       (carry_reg_48), .Q (carry));
  sky130_fd_sc_hd__dfrtp_1 \result_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (\result_reg[1]_37 ), .Q (result[1]));
  sky130_fd_sc_hd__inv_4 g31(.A (n_0), .Y (n_5));
  sky130_fd_sc_hd__inv_4 g35(.A (n_1), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g36(.A (n_7), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g32(.A (n_8), .Y (n_0));
  sky130_fd_sc_hd__dfrtp_2 \b_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (b[2]), .Q (n_3));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[2] (.RESET_B (rst_n), .CLK
       (clk), .D (op[2]), .Q (n_7));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[0] (.RESET_B (rst_n), .CLK
       (clk), .D (op[0]), .Q (n_8));
  sky130_fd_sc_hd__dfrtp_2 \a_reg_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (a[2]), .Q (a_reg[2]));
  sky130_fd_sc_hd__dfrtp_1 \op_reg_reg[1] (.RESET_B (rst_n), .CLK
       (clk), .D (op[1]), .Q (op_reg[1]));
  sky130_fd_sc_hd__dfrtp_2 \a_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (a[3]), .Q (a_reg[3]));
  sky130_fd_sc_hd__dfrtp_2 \a_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (a[1]), .Q (a_reg[1]));
  sky130_fd_sc_hd__dfrtp_1 \a_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (a[0]), .Q (a_reg[0]));
  sky130_fd_sc_hd__dfrtp_2 \b_reg_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (b[3]), .Q (b_reg[3]));
  sky130_fd_sc_hd__dfrtp_2 \b_reg_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (b[0]), .Q (b_reg[0]));
  sky130_fd_sc_hd__dfrtp_1 \b_reg_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (b[1]), .Q (b_reg[1]));
endmodule

