
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 12 2024 07:19:02

// Verification Directory fv/synth_wrapper 

module counter_4bit(clk_i, rst_ni, sel_i, out_o);
  input clk_i, rst_ni, sel_i;
  output [3:0] out_o;
  wire clk_i, rst_ni, sel_i;
  wire [3:0] out_o;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19;
  sky130_fd_sc_hd__dfrtp_1 \out_d_reg[3] (.RESET_B (rst_ni), .CLK
       (clk_i), .D (n_18), .Q (n_19));
  sky130_fd_sc_hd__o2bb2ai_2 g482(.A1_N (n_6), .A2_N (n_17), .B1 (n_6),
       .B2 (n_17), .Y (n_18));
  sky130_fd_sc_hd__dfrtp_2 \out_d_reg[1] (.RESET_B (rst_ni), .CLK
       (clk_i), .D (n_16), .Q (out_o[1]));
  sky130_fd_sc_hd__dfrtp_2 \out_d_reg[2] (.RESET_B (rst_ni), .CLK
       (clk_i), .D (n_15), .Q (out_o[2]));
  sky130_fd_sc_hd__nand2_2 g485(.A (n_13), .B (n_14), .Y (n_17));
  sky130_fd_sc_hd__o2bb2ai_2 g486(.A1_N (n_3), .A2_N (n_10), .B1 (n_3),
       .B2 (n_10), .Y (n_16));
  sky130_fd_sc_hd__o2bb2ai_1 g487(.A1_N (n_5), .A2_N (n_12), .B1 (n_5),
       .B2 (n_12), .Y (n_15));
  sky130_fd_sc_hd__nand4_1 g488(.A (out_o[0]), .B (sel_i), .C
       (out_o[2]), .D (out_o[1]), .Y (n_14));
  sky130_fd_sc_hd__nand4_2 g489(.A (n_0), .B (n_2), .C (n_4), .D (n_1),
       .Y (n_13));
  sky130_fd_sc_hd__nand2_2 g490(.A (n_9), .B (n_11), .Y (n_12));
  sky130_fd_sc_hd__nand3_1 g491(.A (out_o[0]), .B (sel_i), .C
       (out_o[1]), .Y (n_11));
  sky130_fd_sc_hd__nand3_2 g492(.A (n_1), .B (n_2), .C (n_0), .Y (n_9));
  sky130_fd_sc_hd__nand2_2 g493(.A (n_7), .B (n_8), .Y (n_10));
  sky130_fd_sc_hd__dfrtp_2 \out_d_reg[0] (.RESET_B (rst_ni), .CLK
       (clk_i), .D (n_0), .Q (out_o[0]));
  sky130_fd_sc_hd__nand2_1 g495(.A (n_0), .B (out_o[1]), .Y (n_8));
  sky130_fd_sc_hd__nand2_1 g496(.A (n_1), .B (out_o[0]), .Y (n_7));
  sky130_fd_sc_hd__inv_2 g497(.A (out_o[3]), .Y (n_6));
  sky130_fd_sc_hd__clkbuf_2 g498(.A (n_4), .X (n_5));
  sky130_fd_sc_hd__clkinv_1 g499(.A (out_o[2]), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g500(.A (n_2), .Y (n_3));
  sky130_fd_sc_hd__clkinv_2 g501(.A (sel_i), .Y (n_2));
  sky130_fd_sc_hd__inv_4 g502(.A (out_o[1]), .Y (n_1));
  sky130_fd_sc_hd__inv_4 g503(.A (out_o[0]), .Y (n_0));
  sky130_fd_sc_hd__buf_4 drc_bufs509(.A (n_19), .X (out_o[3]));
endmodule

module synth_wrapper(rst_n, clk, sel, out);
  input rst_n, clk, sel;
  output [3:0] out;
  wire rst_n, clk, sel;
  wire [3:0] out;
  wire \out_reg[0]_14 , \out_reg[1]_15 , \out_reg[2]_16 ,
       \out_reg[3]_17 , sel_reg;
  counter_4bit C0(clk, rst_n, sel_reg, {\out_reg[3]_17 , \out_reg[2]_16
       , \out_reg[1]_15 , \out_reg[0]_14 });
  sky130_fd_sc_hd__dfrtp_1 \out_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[3]_17 ), .Q (out[3]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[2]_16 ), .Q (out[2]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[0]_14 ), .Q (out[0]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[1]_15 ), .Q (out[1]));
  sky130_fd_sc_hd__dfrtp_2 sel_reg_reg(.RESET_B (rst_n), .CLK (clk), .D
       (sel), .Q (sel_reg));
endmodule

